Get Available Markets
jzheng2017/spotify-web-api-wrapper pull request #98
Opened 2024-07-11 06:00 UTC by eleonora2687

Get the list of markets where Spotify is available.

2024-07-11 14:29 UTC, jzheng2017 commented
Looks good overall but please fix the whitespace formatting in general for all the files. In addition to that write unit tests for the added functionality. See the existing tests for reference.

2024-07-11 14:34 UTC, jzheng2017 requested changes

2024-07-11 14:34 UTC, jzheng2017 commented on src/main/java/spotify/models/markets/MarketFull.java
> +    public List<String> getAllMarkets() {
I prefer `getMarkets`

2024-07-11 14:34 UTC, jzheng2017 commented on src/main/java/spotify/api/impl/MarketApiRetrofit.java
Fix the whitespace formatting please.

2024-07-11 14:34 UTC, jzheng2017 commented on src/main/java/spotify/models/markets/MarketFull.java
> +    private List<String> markets = new ArrayList<String>() ;
Remove the ArrayList instantiation

2024-07-14 05:54 UTC, eleonora2687 commented
Can you please check the changes i made (whenever you get the time)  and let me know what else should i do next?
i've put A LOT of effort to make all this(the project is big and it it very easy to "get lost" here trying to adapt things here 😓

Thanks in advance

2024-07-21 12:19 UTC, jzheng2017 commented
> Can you please check the changes i made (whenever you get the time) and let me know what else should i do next? i've put A LOT of effort to make all this(the project is big and it it very easy to "get lost" here trying to adapt things here 😓
> 
> Thanks in advance

Thanks. I've been a bit busy so I haven't been able to check. I will review the PR soon. Thanks for the patience.

2024-08-01 16:39 UTC, jzheng2017 commented
PR looks great with no additional comments. Approved for now. I will test it soon and if it works fine then it can be merged.

2024-08-03 08:02 UTC, jzheng2017 commented
I have tested this PR and it works without any issue. It's okay for merge. Thank you for your work.

2024-08-03 08:02 UTC, merged